# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - demo-{{ checksum "package.json" }}

      - run: chmod +x ./setup_libxcb.sh
      - run: sh ./setup_libxcb.sh
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: demo-{{ checksum "package.json" }}

      - run:
          name: Test
          command: |
            sleep 2
            npm run test:ci -- --maxWorkers=2
      - store_artifacts:
          path: test/__image_snapshots__/__diff_output__
          destination: image_snapshot_diff
